title: Hye Bin Park
subtitle: Currently a CS student.
description:

author: Hye Bin Park
email: your-email@example.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "hyebin8rk.github.io" # the base hostname & protocol for your site

# Social settings
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url: https://github.com/hyebin8rk
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
